<?php
get_header(); ?>
    <div class="page-body">
        <div class="page-body__content__pre">
        </div>

        <div class="page-body__content" role="main">
            <div class="conduct-content">
                <div class="conduct-content-heading">
                    <h2><?php _e( "CODICE DI CONDOTTA DELL'ARTISTA", 'streamatemodels' ); ?></h2>
                    <span><?php _e( "Regole, linee guida, cose da fare e da non fare ...", 'streamatemodels'); ?></span>
                    <span><i class="fa fa-calendar"></i><?php _e(" Ultima modifica: 12 aprile 2018", 'streamatemodels'); ?></span>
                    <p><?php _e("Queste linee guida sono in atto per garantire la qualità e l'integrità del nostro sito e dei suoi artisti. Si prega di leggerli attentamente. La violazione di queste linee guida può comportare la sospensione o la chiusura permanente del tuo account con Streamate.", 'streamatemodels'); ?></p>
                </div>
                <div class="conduct-content-text">
                    <div class="conduct-content-text--title"><h3><?php _e( "1. NESSUN TRAFFICO SESSUALE; NESSUNA SOLLECITAZIONE AL CONTATTO PERSONALE CON I CLIENTI", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Illegale e strettamente proibito partecipare, assistere, aiutare, sostenere o agevolare qualsiasi atto di prostituzione, traffico sessuale di minori o traffico a fini sessuali forzati, fraudolenti o coautori. Ció include, senza limitazioni, il divieto di scambiare informazioni personali di contatto con qualsiasi utente o di prendere qualsiasi iniziativa per organizzare qualsiasi tipo di incontro faccia a faccia con un utente. Inoltre, é vietato discutere con un utente qualsiasi transazione che coinvolga qualsiasi altro servizio o prodotto, incluso, ma non limitato a, qualsiasi altro servizio basato su Internet. I conti coinvolti in una di queste attività saranno chiusi e i pagamenti saranno trattenuti.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "2. ACCOUNT DELL'ARTISTA E DELLO STUDIO", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Il tuo account con Streamate può includere solo gli Artisti che si sono registrati nel regolamento e che sono stati approvati da Streamate per apparire sul tuo account. I conti degli Artisti che non si sono registrati correttamente presso Streamate o che non hanno presentato tutta la documentazione richiesta e appropriata saranno definitivamente chiusi. Se non utilizzate più il vostro conto, il vostro conto deve essere chiuso. I conti inattivi verranno chiusi dopo un determinato periodo di tempo e non potranno essere recuperati.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "3. I DOCUMENTI DI CERTIFICAZIONE DELL'ETÀ DEVONO ESSERE PRESENTATI PER TUTTI GLI ARTISTI E GLI STUDIO", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Comparire online, l'utente conferma di aver raggiunto l'età di 18 anni (19 in Canada) per utilizzare il sito web e di aver presentato tutta la documentazione e i certificati necessari per verificare la propria età. Solo coloro che hanno presentato la documentazione appropriata, e che sono stati approvati, possono apparire sulla telecamera", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "4. NIENTE NUDITÁ SOTTO LA CINTURA IN CHAT GRATUITA", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Al fine di evitare l'esposizione dei minori a nudità sotto la cintura e materiale per adulti, non è consentita nudità sotto la cintura nella \"chat libera\". La nudità sotto la cintura è consentita solo nelle aree verificate per età, note anche come \"chat private\" o \"chat a pagamento\". La nudità sotto la cintura nelle aree libere comporterà la sospensione temporanea o la chiusura permanente del tuo account.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "5. NESSUNA VIOLAZIONE DELLE LEGGI IN MATERIA DI OSCENITÀ O DI MINORI", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "L'Artista e/o lo Studio non devono violare gli standard della comunità locale di \"oscenitá\" in qualsiasi prestazione relativa al presente Contratto, incluso, ma non limitato a, l'Artista e/o lo Studio non devono descrivere o descrivere alcun atto di natura sessuale che coinvolga bestialitá, necrofilia, coprofilia, urina, feci, vomito, sangue o simili. Inoltre, durante qualsiasi performance relativa al presente Contratto, l'Artista e/o lo Studio non deve descrivere o descrivere alcuna attività o atto di natura sessuale di un minorenne, che coinvolga persone di età inferiore ai 18 anni (incluso, ma non limitato a, sesso di qualsiasi tipo, sesso simulato, condotta, masturbazione, schiavitú, dominazione, sadomasochismo o altro).", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "6. NESSUNA PROMOZIONE DI ALTRI SITI", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "La promozione diretta di qualsiasi sito web non legato a Streamate ai membri di Streamate e ai membri dei siti affiliati a Streamate é severamente proibita. Ció include, ma non si limita alle discussioni online, ai testi o a qualsiasi altro mezzo. La violazione di questa condizione comporterà la risoluzione del presente Contratto e la chiusura definitiva del vostro conto. Inoltre, Streamate si riserva il diritto di trattenere i pagamenti in caso di violazione di questa condizione.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "7. VIETATO ESIBIRSI SOTTO L'INFLUENZA DI ALCOOL O DI DROGHE ILLEGALI", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Durante l'esecuzione di uno spettacolo o l'esecuzione di qualsiasi altra azione relativa al presente Contratto, l'Artista e/o lo Studio non devono essere sotto l'influenza di alcol, droghe illegali o sostanze stupefacenti illegali.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "8. NESSUN ANIMALE DOMESTICO O ARMA DA FUOCO SULLE CAMME", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Durante qualsiasi spettacolo, é vietato all'Artista e/o allo Studio di far apparire un animale nella webcam o di far apparire un'arma da fuoco o qualsiasi arma durante lo spettacolo.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "9. NESSUNA ATTIVITÁ FRAUDOLENTA", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Durante l'esecuzione di uno spettacolo o l'esecuzione di qualsiasi altra azione relativa al presente Contratto, l'Artista e/o lo Studio non devono intraprendere alcuna attività fraudolenta. Per attività fraudolenta si intende qualsiasi attività sul sito che comporti reclami o addebiti o che sia considerata inappropriata dai rappresentanti di Streamate. Streamate si riserva il diritto di chiudere qualsiasi conto in qualsiasi momento e per qualsiasi motivo, in caso di sospetto di frode e di non effettuare pagamenti correlati.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "10. L'APPROVAZIONE DELL'IMMAGINE", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Le immagini inviate per la biografia dell'artista e/o dello studio Streamate devono essere preapprovate da Streamate. Le immagini di natura grafica o contenenti \"nuditá sotto la cintura\" non saranno approvate. Streamate si riserva il diritto di approvare o rifiutare qualsiasi immagine inviata.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "11. NON CONCORRENZA", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Streamate accetta che l'Artista sia autorizzato a possedere e gestire un sito web personale. A condizione che l'Artista si impegni a non sollecitare clienti e/o altri Artisti sul suo sito web personale che é, o potrebbe essere, in concorrenza diretta o indiretta con Streamate. L'Artista si impegna inoltre a non divulgare ad alcuna persona indirizzi e-mail o indirizzi di pagine web senza l'esplicita approvazione di Streamate.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "12. MOLESTIE NEI CONFRONTI DEGLI ARTISTI", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Streamate non tollera le molestie degli Artisti tra di loro. Se sembra che tu stia molestando, infastidendo, prendendo in giro, distraendo e/o prendendo in giro altri Artisti (come Artista o Membro), il tuo account può essere sospeso o chiuso. Streamate sostiene tutti gli Artisti e vuole che tutti abbiano successo. Ci aspettiamo che tutti gli Artisti siano maturi e si sostengano a vicenda.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "13. CHIUSURA DEL CONTO", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Se non utilizzate più il vostro conto, il vostro conto deve essere chiuso. I conti inattivi saranno archiviati dopo un determinato periodo di tempo e non potranno essere recuperati. Gli account Streamate Artist possono essere chiusi in base al livello di performance o alla qualità. Gli artisti devono sforzarsi di mantenere un livello ragionevole di performance nelle discussioni online in relazione al tempo trascorso nelle comunicazioni a pagamento.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "14. MODIFICA DELLE REGOLE", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Ci riserviamo il diritto di aggiungere o modificare eventuali regole o linee guida, se necessario.", 'streamatemodels' ); ?></p>
                </div>
             </div>
        </div>
    </div>
<?php
get_footer();
