<?php
get_header(); ?>
    <div class="page-body">
        <div class="page-body__content__pre">
        </div>

        <div class="page-body__content" role="main">
            <div class="conduct-content">
                <div class="conduct-content-heading">
                    <h2><?php _e( "GEDRAGSCODE VAN DE PERFORMER", 'streamatemodels' ); ?></h2>
                    <span><?php _e( "Regels, richtlijnen, do's en don'ts ...", 'streamatemodels'); ?></span>
                    <span><i class="fa fa-calendar"></i><?php _e(" Laatste wijziging: 12 april 2018", 'streamatemodels'); ?></span>
                    <p><?php _e("Deze richtlijnen zijn opgesteld om de kwaliteit en integriteit van onze site en van onze performers te waarborgen. Lees ze aandachtig door. Overtreding van deze richtlijnen kan leiden tot opschorting of permanente sluiting van uw account bij Streamate.", 'streamatemodels'); ?></p>
                </div>
                <div class="conduct-content-text">
                    <div class="conduct-content-text--title"><h3><?php _e( "1. GEEN SEKSHANDEL; GEEN VERZOEK OM PERSOONLIJK CONTACT MET KLANTEN", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Het is illegaal en ten strengste verboden om deel te nemen aan, te ondersteunen of te faciliteren in de vorm van prostitutie, handel in kinderseks of mensenhandel voor gedwongen, frauduleuze of dwingende seksuele doeleinden. Dit omvat, zonder beperking, dat het u verboden is persoonlijke contactgegevens uit te wisselen met een gebruiker, of om stappen te ondernemen om elk type persoonlijke ontmoeting met een gebruiker te regelen. Bovendien is het verboden om met een gebruiker een transactie te bespreken die betrekking heeft op een andere dienst of product, inclusief, maar niet beperkt tot, enige andere op internet gebaseerde dienst. Accounts die bij een van deze activiteiten betrokken zijn, worden beëindigd en betalingen worden ingehouden.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "2. PERFORMERS EN STUDIO-ACCOUNTS", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Uw account bij Streamate kan alleen performers bevatten die zich hebben geregistreerd voor de regels en die door Streamate zijn goedgekeurd om op uw account te verschijnen. Accounts van performers die niet correct zijn geregistreerd bij Streamate of die niet alle vereiste en geschikte documentatie hebben ingediend, worden permanent gesloten. Als u uw account niet meer gebruikt, moet uw account worden gesloten. Inactieve accounts worden na een bepaalde periode gesloten en kunnen niet worden hersteld.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "3. LEEFTIJD BEWIJSDOCUMENTEN MOETEN VOOR ALLE PERFORMERS EN STUDIO'S WORDEN INGEDIEND", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Door live te verschijnen, bevestigt u dat u de leeftijd van 18 (19 in Canada) hebt bereikt om de website te gebruiken en dat u alle relevante documentatie en certificaten heeft ingediend om uw leeftijd te verifiëren. Alleen mensen die de juiste documentatie hebben ingediend en die zijn goedgekeurd, kunnen op de camera verschijnen.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "4. GEEN NUDITEIT ONDER DE TAILLE IN GRATIS CHAT", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Om blootstelling van minderjarigen aan naaktheid onder de taille en materiaal voor volwassenen te voorkomen, is naaktheid onder de taille verboden in de \"free chat \". Onder de taille is naaktheid alleen toegestaan ​​in door leeftijd geverifieerde gebieden, ook wel bekend als \"private chat \" of \"paid chat \". Naaktheid onder de taille in open toegangsgebieden zal resulteren in de tijdelijke opschorting of permanente sluiting van uw account.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "5. GEEN SCHENDING VAN WETTEN MET BETREKKING TOT OBSCENITEIT OF MINDERJARIGEN", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "De performer en / of studio mag de lokale gemeenschapsnormen voor \"obsceniteit \" niet schenden in enige uitvoering met betrekking tot deze overeenkomst, inclusief, maar niet beperkt tot, performer en / of studio mag geen handeling van seksuele aard vertegenwoordigen of beschrijven waarbij bestialiteit, necrofilie, coprofilie, urine, uitwerpselen, braaksel, bloed en dergelijke. Bovendien mogen Performer en / of Studio tijdens een show met betrekking tot dit contract geen enkele activiteit of handeling van seksuele aard vertegenwoordigen of beschrijven door een minderjarige, waarbij personen onder de 18 zijn betrokken (inclusief, maar niet beperkt tot, het geslacht van elke soort, gesimuleerde seks, gedrag, masturbatie, slavernij, overheersing, sadomasochisme of anderen).", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "6. GEEN PROMOTIE VANAF ANDERE SITES", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Directe promotie van een niet-Streamate-website aan Streamate-leden en leden van aan Streamate gelieerde sites is ten strengste verboden. Dit omvat, maar is niet beperkt tot, online discussies, teksten of andere middelen. Overtreding van deze voorwaarde zal resulteren in de beëindiging van deze overeenkomst en de permanente beëindiging van uw account. Bovendien behoudt Streamate zich het recht voor om betalingen in te houden wegens schending van deze voorwaarde.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "7. HET IS VERBODEN OM PRESTATIES TE DOEN ONDER INVLOED VAN ALCOHOL OF ILLEGALE DRUGS", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Tijdens het geven van een show of het ondernemen van enige andere actie met betrekking tot deze overeenkomst, mogen de performer en / of de studio niet onder invloed zijn van alcohol, illegale drugs of gereguleerde stoffen.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "8. GEEN DIEREN OF GEWERP OP CAM", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Tijdens een show is het de Performer en / of de Studio verboden om een ​​dier op de camera te tonen en om enig vuurwapen of enig wapen op de camera te tonen.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "9. GEEN FRAUDULENTE ACTIVITEIT", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Tijdens het geven van een show of het ondernemen van enige andere actie met betrekking tot dit contract, mogen de performer en / of de studio geen frauduleuze activiteiten ontplooien. Frauduleuze activiteit wordt gedefinieerd als elke activiteit op de site die resulteert in klachten of terugboekingen of die door vertegenwoordigers van Streamate als ongepast wordt beschouwd. Streamate behoudt zich het recht voor om elk account op elk moment en om welke reden dan ook te beëindigen als fraude wordt vermoed en geen gerelateerde betalingen te doen.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "10. FOTO GOEDKEURING", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Afbeeldingen die zijn ingezonden voor de Streamate-performer en / of Studio-biografie moeten vooraf worden goedgekeurd door Streamate. Afbeeldingen die grafisch van aard zijn of \"naaktheid onder de taille \" bevatten, worden niet goedgekeurd. Streamate behoudt zich het recht voor om een ​​ingezonden afbeelding goed te keuren of te weigeren.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "11. NIET-CONCURRENTIE", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Streamate accepteert dat de performer bevoegd is om een ​​persoonlijke website te bezitten en te exploiteren. Op voorwaarde dat deze performer ermee instemt om geen klanten en / of andere performers te werven op zijn persoonlijke website die daarom rechtstreeks of onrechtstreeks met Streamate concurreert of zou kunnen zijn. De performer stemt er verder mee in om geen e-mailadressen of webpagina-adressen aan iemand bekend te maken zonder de uitdrukkelijke toestemming van Streamate.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "12. INTIMIDATIE VAN PERFORMERS", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Streamate tolereert geen intimidatie door performers onder elkaar. Als blijkt dat u andere performers lastigvalt, stoort, plaagt, afleidt en / of voor de gek houdt (als performer of lid), kan uw account worden opgeschort of beëindigd. Streamate ondersteunt alle performers en wil dat iedereen succesvol is. We verwachten van alle performers dat ze zich volwassen gedragen en elkaar steunen.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "13.BEËINDIGING VAN DE ACCOUNT", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Als u uw account niet meer gebruikt, moet uw account worden gesloten. Inactieve accounts worden na een bepaalde tijd gearchiveerd en kunnen niet worden hersteld. Streamate Performer-accounts kunnen worden beëindigd op basis van prestatie- of kwaliteitsniveau. Kunstenaars moeten ernaar streven om een ​​redelijk prestatieniveau te behouden in online discussies in verhouding tot de tijd besteed aan betaalde communicatie.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "14. WIJZIGING VAN DE REGELS", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "We behouden ons het recht voor om regels of richtlijnen naar behoefte toe te voegen of te wijzigen.", 'streamatemodels' ); ?></p>
                </div>
             </div>
        </div>
    </div>
<?php
get_footer();
