<?php
get_header(); ?>
    <div class="page-body">
        <div class="page-body__content__pre">
        </div>

        <div class="page-body__content" role="main">
            <div class="conduct-content">
                <div class="conduct-content-heading">
                    <h2><?php _e( "CODE DE CONDUITE DE L'ARTISTE", 'streamatemodels' ); ?></h2>
                    <span><?php _e( "Règles, directives, choses à faire et à ne pas faire...", 'streamatemodels'); ?></span>
                    <span><i class="fa fa-calendar"></i><?php _e(" Dernière modification: 12 avril 2018", 'streamatemodels'); ?></span>
                    <p><?php _e("Ces directives sont en place pour assurer la qualité et l'intégrité de notre site et de ses Artistes. Veuillez les lire attentivement. La violation de ces directives peut entraîner la suspension ou la fermeture définitive de votre compte avec Streamate.", 'streamatemodels'); ?></p>
                </div>
                <div class="conduct-content-text">
                    <div class="conduct-content-text--title"><h3><?php _e( "1. AUCUN TRAFIC DE SEXE; PAS DE SOLLICITATION DE CONTACT PERSONNEL AVEC LES CLIENTS", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Il est illégal et strictement interdit de participer, d'assister, d'aider, de soutenir ou de faciliter tout acte de prostitution, de trafic à caractère sexuel d'enfants ou de trafic à des fins sexuelles forcé, frauduleux ou coercitif. Ceci inclut, sans limitation, qu'il vous est interdit d'échanger des informations de contact personnelles avec tout utilisateur, ou de prendre toute mesure pour organiser tout type de réunion en face-à-face avec un utilisateur. En outre, il vous est interdit de discuter avec un utilisateur de toute transaction impliquant tout autre service ou produit, y compris, sans toutefois s'y limiter, tout autre service basé sur Internet. Les comptes impliqués dans l'une de ces activités seront résiliés et les paiements seront retenus.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "2. COMPTES D'ARTISTE ET DE STUDIO", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Votre compte avec Streamate ne peut inclure que les Artistes qui se sont inscrits dans les règles et qui sont approuvés par Streamate pour apparaître sur votre compte. Les comptes des Artistes qui ne se sont pas correctement enregistrés auprès de Streamate ou qui n'ont pas soumis toute la documentation requise et appropriée seront fermés de manière permanente. Si vous n'utilisez plus votre compte, votre compte doit être fermé. Les comptes inactifs seront fermés après un laps de temps déterminé et ne pourront plus être récupérés.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "3. LES DOCUMENTS CERTIFIANT L'ÂGE DOIVENT ÊTRE SOUMIS POUR TOUS LES ARTISTES ET STUDIOS", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "En apparaissant en direct, vous confirmez que vous avez atteint l'âge de 18 ans (19 ans au Canada) pour utiliser le site Web, et que vous avez soumis toute la documentation appropriée et les certificats vérifiant votre âge. Seules les personnes ayant soumis la documentation appropriée, et qui ont été approuvées, peuvent apparaître sur la caméra.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "4. PAS DE NUDITÉ AU-DESSOUS DE LA TAILLE DANS LE CHAT GRATUIT", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Afin d'éviter l'exposition des mineurs à la nudité au-dessous de la taille et au matériel pour adultes, la nudité au-dessous de la taille est interdite dans la \"discussion libre\". Au-dessous de la taille, la nudité n'est autorisée que dans les zones où l'âge est vérifié, également appelées \"discussions privées\" ou \"discussions payantes\". La nudité au-dessous de la taille dans les zones à libre accès entraînera la suspension temporaire ou la fermeture définitive de votre compte.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "5. AUCUNE VIOLATION DES LOIS RELATIVES À L'OBSCÉNITÉ OU AUX MINEURS", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "L'Artiste et/ou le Studio ne doit pas enfreindre les normes de la communauté locale en matière \"d'obscénité\" lors d'une performance liée au présent Contrat, y compris, mais sans s'y limiter, Artiste et/ou Studio ne doit pas représenter ni décrire d'acte de nature sexuelle impliquant la bestialité, la nécrophilie, la coprophilie, l'urine, excréments, vomissures, sang ou autres. De plus, au cours de tout spectacle lié au présent Contrat, Artist et/ou Studio ne doit représenter ni décrire une activité ou un acte à caractère sexuel de mineur, impliquant des personnes de moins de 18 ans (y compris, sans toutefois s'y limiter, le sexe de quelque nature que ce soit, le sexe simulé, conduite, masturbation, esclavage, domination, sadomasochisme ou autres).", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "6. AUCUNE PROMOTION D'AUTRES SITES", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "La promotion directe de tout site Web non lié à Streamate auprès des membres de Streamate et des membres de sites affiliés de Streamate est strictement interdite. Ceci inclut, sans toutefois s'y limiter, les discussions en ligne, les textes ou tout autre moyen. La violation de cette condition entraînera la résiliation du présent Contrat et la résiliation définitive de votre compte. En outre, Streamate se réserve le droit de retenir des paiements en cas de violation de cette condition.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "7. IL EST INTERDIT DE FAIRE UNE PERFORMANCE SOUS INFLUENCE D'ALCOOL OU DE DROGUES ILLÉGALES", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Tout en donnant un spectacle ou en prenant toute autre action liée à ce Contrat, L'Artiste et/ou le Studio ne doit pas être sous l'influence de l'alcool, de drogues illicites ou de substances contrôlées.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "8. PAS D'ANIMAUX OU D'ARMES À FEU SUR CAM", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Lors de toute représentation, il est interdit à l'Artiste et/ou au Studio de faire apparaître un animal sur la caméra et de faire apparaître une arme à feu ou une arme quelconque sur la caméra.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "9. PAS D'ACTIVITÉ FRAUDULEUSE", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Tout en donnant un spectacle ou en prenant toute autre action liée à ce Contrat, L'Artiste et/ou le Studio ne doit s'engager dans aucune activité frauduleuse. Une activité frauduleuse est définie comme toute activité sur le site qui entraîne des plaintes ou des rejets de débit ou qui est jugée inappropriée par les représentants de Streamate. Streamate se réserve le droit de résilier n'importe quel compte à tout moment pour quelque raison que ce soit si une fraude est suspectée et de ne pas effectuer de paiements connexes.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "10. APPROBATION D'IMAGE", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Les images soumises pour la biographie Streamate de l'Artiste et/ou du Studio doivent être approuvées au préalable par Streamate. Les images de nature graphique ou contenant de la \"nudité au-dessous de la taille\" ne seront pas approuvées. Streamate se réserve le droit d'approuver ou de rejeter toute image soumise.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "11. NON-CONCURRENCE", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Streamate accepte que l'Artiste soit autorisé à posséder et à exploiter un site Web personnel. Sous réserve que cet Artiste accepte de ne pas solliciter des clients et/ou d'autres Artistes sur son site Web personnel qui est de ce fait, ou pourrait être, en concurrence directe ou indirecte avec Streamate. L'Artiste s'engage en outre à ne divulguer à aucune personne des adresses électroniques ou des adresses de pages Web sans l'approbation explicite de Streamate.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "12. HARCÈLEMENT D'ARTISTES", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Streamate ne tolère pas le harcèlement des Artistes entre eux. S'il s'avère que vous harcelez, dérangez, taquinez, distrayez et / ou que vous vous moquez d'autres Artistes (en tant qu'Artiste ou membre), votre compte peut être suspendu ou résilié. Streamate prend en charge tous les Artistes et veut que tout le monde réussisse. Nous nous attendons à ce que tous les Artistes se comportent avec maturité et se soutiennent mutuellement.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "13. RÉSILIATION DU COMPTE", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Si vous n'utilisez plus votre compte, votre compte doit être fermé. Les comptes inactifs seront archivés après un temps déterminé et ne pourront pas être récupérés. Les comptes d'Artistes Streamate peuvent être résiliés en fonction du niveau de performance ou de la qualité. Les Artistes doivent s'efforcer de maintenir un niveau de performance raisonnable dans les discussions en ligne en rapport au temps passé en communication payante.", 'streamatemodels' ); ?></p>
                    <div class="conduct-content-text--title"><h3><?php _e( "14. MODIFICATION DES RÈGLES", 'streamatemodels' ); ?></h3></div>
                    <p><?php _e( "Nous nous réservons le droit d'ajouter ou de modifier toute règle ou directive en cas de besoin.", 'streamatemodels' ); ?></p>
                </div>
             </div>
        </div>
    </div>
<?php
get_footer();
